# 端口
server:
  port: 8443

# mysql配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # es配置
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch

# mybatis-plus配置
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.example.shop.domain
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: input